spring.application.name=clyvovet

# Configuração do Banco de Dados (Azure SQL / SQL Server via Variáveis de Ambiente)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA e Hibernate (Dialeto do Azure SQL)
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Segurança JWT
jwt.secret=Q0xZVk9WRVRfQ0hBVkVfU0VDUkVUQV9QQVJBX0FVVEVOVElDQUNBT19KV1RfMjAyNl9TRUdVUkE=
jwt.expiration=86400000